# Docker Compose Configuration for Dragonfly Application
# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md

# From project root, run with:
#   docker compose --file .build/docker-compose.yml up --detach

# Define services.
services:
  # Service for the www container.
  www:
    # Container name for easy identification.
    container_name: www

    # Docker image for the Dragonfly www service.
    image: docker.io/webpwnized/dragonfly:www

    # Intentionally run the container as root for SAST testing.
    user: root

    # Prevent processes from gaining additional privileges.
    security_opt:
      - no-new-privileges:true

    # Port mappings.
    ports:
      # Map host port 80 to container port 80 on localhost.
      - 127.0.0.1:80:80

      # Map host port 8888 to container port 80 for DAST scanning.
      - 127.0.0.1:8888:80

    # Connect the service to the HTTP network.
    networks:
      - httpnet

# Define networks.
networks:
  # Network segment for HTTP communication between containers.
  httpnet: