# Docker Compose Configuration for Dragonfly Application
# Documentation: https://github.com/compose-spec/compose-spec/blob/master/spec.md

# From project root, run with:
#   docker compose --file .build/docker-compose.yml up --detach

# Define the version of Docker Compose syntax being used
version: '3.8'

# Define services
services:
  # Service for the www container
  www:
    # Container name for easy identification
    container_name: www
    # Docker image for the dragonfly www service
    image: docker.io/webpwnized/dragonfly:www
    
    # Port mapping: maps host ports to container ports
    ports:
      # Map host port 80 to container port 80 (localhost only)
      - 127.0.0.1:80:80
      # Map host port 8888 to container port 80 for DAST scan (localhost only)
      - 127.0.0.1:8888:80
      
    # Network configuration: connects the www service to the httpnet network
    networks:
      - httpnet

# Define networks
networks:
  # Network segment for HTTP communication
  httpnet:
    # This network segment is used for HTTP communication between containers